default:
  tags:
    - smarty-road-runner

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --settings ci_settings.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -Dquarkus.container-image.build=true
    -Dquarkus.container-image.push=true
    -Dquarkus.container-image.insecure=true
    -Dquarkus.container-image.registry=${CI_REGISTRY}
    -Dquarkus.container-image.username=${CI_REGISTRY_USER}
    -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}
    -Dquarkus.container-image.tag=${CI_COMMIT_SHORT_SHA}
  JGITVER_BRANCH: $CI_COMMIT_REF_NAME # provides jgitver the current branch even on detached head

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - release

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - DOCKER_TAG=$(echo "${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}" | sed "s|\/|-|g")
    - mvn $MAVEN_CLI_OPTS -Dquarkus.container-image.additional-tags=${DOCKER_TAG} clean deploy
    - echo "Image pushed to registry ${APP_REGISTRY_IMAGE}:${DOCKER_TAG}"
  tags:
    - smarty-road-runner
  rules:
    - when: always
  artifacts:
    when: always
    expire_in: 1 days
    paths:
      - '**/target/surefire-reports/*.xml'
      - '**/target/failsafe-reports/*.xml'
    reports:
      junit:
        - '**/target/surefire-reports/*.xml'
        - '**/target/failsafe-reports/*.xml'